# Add 'RFC' label to any changes within 'rfc' folder or any subfolders
# Used by https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/main/.github/workflows/pull_request_labeler.yml
RFC:
- rfc/**/*
- '!rfc/README.md'
