graph LR
  subgraph SA [Implicit Trust]
    direction LR
      A11((User)) --  SOCKS/VPN --> B11{Kubernetes\nIngress}
      B11 --> C11(MS1) --> D11(PEP1):::fillPEP
      B11 --> C12(MS2) --> D12(PEP2):::fillPEP
      B11 --> C13(MS...)
      B11 --> C14[/Discovery/]:::fillDisco --> D14(...)
      classDef fillDisco fill:violet
      classDef fillPEP fill:#f96
  end
  subgraph SB [Explicit Trust]
    direction LR
      A21((User)) --  SOCKS/VPN --> B21{Kubernetes\nIngress\nPEP}:::fillPEP
      B21 --> C21(MS1)
      B21 --> C22(MS2)
      B21 -.-x C23(MS...)
      B21 -.-x C24[/Discovery/]
  end
  SA-->SB